version: 2.1

jobs:
  semgrep-scan:
    parameters: 
      repo_path:
        type: string
        default: fcaeyacc/nft-secondary-market
      diff_branch:
        type: string
        default: 

    environment:
      # SEMGREP_RULES: >- # more at semgrep.dev/explore
        # p/security-audit
        # p/secrets

        # Scan changed files in PRs, block on new issues only (existing issues ignored)
      # SEMGREP_BASELINE_REF: << parameters.diff_branch >>

        # == Optional settings in the environment: block

      # Instead of SEMGREP_RULES:, use rules set in Semgrep App.
      # Get your token from semgrep.dev/manage/settings.
      # SEMGREP_APP_TOKEN: {SEMGREP_APP_TOKEN}
      SEMGREP_REPO_NAME: << parameters.repo_path >>
      SEMGREP_REPO_URL: << pipeline.project.git_url >>
      SEMGREP_BRANCH: << pipeline.git.branch >>

      # Change job timeout (default is 1800 seconds; set to 0 to disable)
      # SEMGREP_TIMEOUT: 300

    docker:
      - image: returntocorp/semgrep-agent:v1
    steps:
      - checkout
      - run:
          name: "Semgrep scan"
          command: semgrep-agent
workflows:
  Semgrep:
    jobs:
      - semgrep-scan